# golangci-lint configuration for Scanfrog
# Focuses on game development best practices and terminal UI concerns

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - interactive

linters:
  enable:
    # Default linters
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters for quality
    - gocyclo       # Cyclomatic complexity
    - gocognit      # Cognitive complexity  
    - bodyclose     # HTTP response body closed
    - prealloc      # Preallocate slices where possible
    - revive        # More comprehensive than golint
    
    # Security
    - gosec         # Security checks

    # Error handling
    - errcheck      # Check error returns
    - errorlint     # Error wrapping

    # Performance (important for games)
    - gocritic      # Various checks

linters-settings:
  gocyclo:
    min-complexity: 15  # Games can have complex update loops

  gocognit:
    min-complexity: 20  # Allow for game logic complexity

  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = err in some cases
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentedOutCode  # Allow during development
      - whyNoLint        # Don't require explanations

  gosec:
    excludes:
      - G104  # Duplicates errcheck
      - G304  # File path provided by user is OK

  revive:
    enable-all-rules: false
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: var-declaration
      - name: var-naming

issues:
  exclude-rules:
    # Allow complex functions in game logic
    - path: internal/game/update.go
      linters:
        - gocyclo
        - gocognit

    # Allow complex rendering logic
    - path: internal/game/render.go
      linters:
        - gocyclo
        - gocognit

    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocyclo

    # Allow magic numbers in game mechanics
    - path: internal/game/
      text: "magic number"

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Maximum count of issues with the same text
  max-same-issues: 3
